services:
  web:
    build: .
    expose:
      - "8002"
    env_file:
      - .env
    volumes:
      - bassinga_static:/app/staticfiles
    restart: always
    networks:
      - shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bassinga_static:
    external: true

networks:
  shared:
    external: true
    name: shared_network