services:
  web:
    build: .
    expose:
      - "8002"
    env_file:
      - .env
    volumes:
      - bassinga_static:/app/staticfiles
    restart: always
    networks:
      - shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"