server {
    listen 80;
    server_name bassinga.com www.bassinga.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bassinga.com www.bassinga.com;

    ssl_certificate /etc/letsencrypt/live/bassinga.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bassinga.com/privkey.pem;

    location /static/ {
        alias /app/bassinga_staticfiles/;
    }

    location / {
        proxy_pass http://bassinga-web-1:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}