# Generated by Django 6.0.2 on 2026-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FretTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('E', models.TextField()),
                ('A', models.TextField()),
                ('D', models.TextField()),
                ('G', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('E', models.TextField()),
                ('A', models.TextField()),
                ('D', models.TextField()),
                ('G', models.TextField()),
            ],
        ),
    ]
