# Generated by Django 6.0.2 on 2026-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frettab',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='notetab',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='frettab',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notetab',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
