# Generated by Django 6.0.2 on 2026-02-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0002_alter_frettab_options_alter_notetab_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteTab',
        ),
    ]
